config/routes.rb
FjaInvoice::Application.routes.draw do
  root :to => 'employees#index'

  resources :timesheets

  resources :time_tracks

  resources :tasks

  resources :employees

end

app/models/timesheet.rb
class Timesheet < ActiveRecord::Base
  attr_accessible :employee_id, :enddate, :hours, :task

  belongs_to :employee
end

app/controllers/timesheets_controller.rb
class TimesheetsController < ApplicationController
  # GET /timesheets
  # GET /timesheets.json
  def index
    @timesheets = Timesheet.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @timesheets }
    end
  end

  # GET /timesheets/1
  # GET /timesheets/1.json
  def show
    @timesheet = Timesheet.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @timesheet }
    end
  end

  # GET /timesheets/new
  # GET /timesheets/new.json
  def new
    @timesheet = Timesheet.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @timesheet }
    end
  end

  # GET /timesheets/1/edit
  def edit
    @timesheet = Timesheet.find(params[:id])
  end

  # POST /timesheets
  # POST /timesheets.json
  def create
    @timesheet = Timesheet.new(params[:timesheet])

    respond_to do |format|
      if @timesheet.save
        format.html { redirect_to @timesheet, notice: 'Timesheet was successfully created.' }
        format.json { render json: @timesheet, status: :created, location: @timesheet }
      else
        format.html { render action: "new" }
        format.json { render json: @timesheet.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /timesheets/1
  # PUT /timesheets/1.json
  def update
    @timesheet = Timesheet.find(params[:id])

    respond_to do |format|
      if @timesheet.update_attributes(params[:timesheet])
        format.html { redirect_to @timesheet, notice: 'Timesheet was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @timesheet.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /timesheets/1
  # DELETE /timesheets/1.json
  def destroy
    @timesheet = Timesheet.find(params[:id])
    @timesheet.destroy

    respond_to do |format|
      format.html { redirect_to timesheets_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/timesheets_helper.rb
module TimesheetsHelper
end

app/views/timesheets/_form.html.erb
<%= form_for(@timesheet) do |f| %>
  <% if @timesheet.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@timesheet.errors.count, "error") %> prohibited this timesheet from being saved:</h2>

      <ul>
      <% @timesheet.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :task %><br />
    <%= f.text_field :task %>
  </div>
  <div class="field">
    <%= f.label :hours %><br />
    <%= f.text_field :hours %>
  </div>
  <div class="field">
    <%= f.label :enddate %><br />
    <%= f.date_select :enddate %>
  </div>
  <div class="field">
    <%= f.label :employee_id %><br />
    <%= f.number_field :employee_id %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/timesheets/edit.html.erb
<h1>Editing timesheet</h1>

<%= render 'form' %>

<%= link_to 'Show', @timesheet %> |
<%= link_to 'Back', timesheets_path %>

app/views/timesheets/index.html.erb
<h1>Listing timesheets</h1>

<table>
  <tr>
    <th>Task</th>
    <th>Hours</th>
    <th>Enddate</th>
    <th>Employee</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @timesheets.each do |timesheet| %>
  <tr>
    <td><%= timesheet.task %></td>
    <td><%= timesheet.hours %></td>
    <td><%= timesheet.enddate %></td>
    <td><%= timesheet.employee_id %></td>
    <td><%= link_to 'Show', timesheet %></td>
    <td><%= link_to 'Edit', edit_timesheet_path(timesheet) %></td>
    <td><%= link_to 'Destroy', timesheet, method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Timesheet', new_timesheet_path %>

app/views/timesheets/new.html.erb
<h1>New timesheet</h1>

<%= render 'form' %>

<%= link_to 'Back', timesheets_path %>

app/views/timesheets/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Task:</b>
  <%= @timesheet.task %>
</p>

<p>
  <b>Hours:</b>
  <%= @timesheet.hours %>
</p>

<p>
  <b>Enddate:</b>
  <%= @timesheet.enddate %>
</p>

<p>
  <b>Employee:</b>
  <%= @timesheet.employee_id %>
</p>


<%= link_to 'Edit', edit_timesheet_path(@timesheet) %> |
<%= link_to 'Back', timesheets_path %>